services:
  # Spring Boot app
  app:
    build:
      context: .
      dockerfile: Dockerfile.${PROFILE:-dev}
    ports:
      - "8080:8080" # Exposing default Spring Boot port
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-dev}
    depends_on:
      - db
    volumes:
      - ./src:/app/src  # Map the source code to /app/src inside the container
      - ./target:/app/target  # For compiled classes
      - /app/.m2  # Optional: to cache Maven dependencies
    networks:
      - hotel-network

  # PostgreSQL database
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mm
      - POSTGRES_DB=HotelBookingSystem
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hotel-network

volumes:
  postgres-data:
    driver: local

networks:
  hotel-network:
    driver: bridge