services:
  # Spring Boot app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Exposing default Spring Boot port
    develop:
      watch:
        - action: rebuild
          path: .
  #  env_file:
  #    - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - APP_NAME=${APP_NAME}
    depends_on:
      - db
    volumes:
      - ./src:/app/src  # Map the source code to /app/src inside the container
      - ./target:/app/target  # For compiled classes
      - /app/.m2  # Optional: to cache Maven dependencies
    networks:
      - hotel-network

  # PostgreSQL database
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hotel-network

volumes:
  postgres-data:
    driver: local

networks:
  hotel-network:
    driver: bridge